language: objective-c
osx_image: xcode8

script:
  - xctool
    -project SwiftGif.xcodeproj -scheme SwiftGif
    -sdk iphonesimulator
    -destination "platform=iOS Simulator,name=iPhone 6" build test
    CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=""
